/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Avatar.glb -t 
*/
"use client";
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    xuantra_1: THREE.Mesh
    xuantra_2: THREE.Mesh
  }
  materials: {
    Handle1Mtl: THREE.MeshStandardMaterial
    Xuantra1Mtl: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3Dassets/Avatar.glb') as unknown as GLTFResult
  // const groupRef = useRef<THREE.Group>(null)
  const mesh1Ref = useRef<THREE.Mesh>(null)
  const mesh2Ref = useRef<THREE.Mesh>(null)
  const Y_OFFSET = 1

  useFrame((state) => {
    if (mesh1Ref.current ) {
      const time = state.clock.getElapsedTime() 
      // groupRef.current.rotation.y = time * 0.3  
      // groupRef.current.rotation.x = Math.sin(time * 0.5) * 0.2 

      // const rotationZ = time*0.3
      const rotationZ = time*0.1
      const rotationY = 0  
      const rotationX = 0

      if (mesh1Ref.current) {
        mesh1Ref.current.rotation.y = rotationY
        mesh1Ref.current.rotation.x = rotationX
        mesh1Ref.current.rotation.z= rotationZ
      }

      if (mesh2Ref.current) {
        mesh2Ref.current.rotation.y = rotationY
        mesh2Ref.current.rotation.x = rotationX
        mesh2Ref.current.rotation.z = rotationZ
      }
    }
  })

  return (
    // <group {...props} dispose={null} scale={[1, 1, 1]}>
    //   <mesh geometry={nodes.xuantra_1.geometry} material={materials.Handle1Mtl} />
    //   <mesh geometry={nodes.xuantra_2.geometry} material={materials.Xuantra1Mtl} />
    // </group>
    <group  {...props} dispose={null} scale={[2, 2, 2]} rotation={[Math.PI/2, 0, Math.PI]}>
      {/* <group position={[0, -Y_OFFSET, 0]} > */}
      <group>
       {/* Mesh 1: (Handle) */}
        <mesh ref = {mesh1Ref} geometry={nodes.xuantra_1.geometry}>
          <meshStandardMaterial
            {...materials.Handle1Mtl}
            transparent={false}
            depthWrite={true}
            depthTest={true}
            side={THREE.FrontSide}
          />
        </mesh>

        {/* Mesh 2: (Xuantra) */}
        <mesh ref = {mesh2Ref} geometry={nodes.xuantra_2.geometry}>
          <meshStandardMaterial
            {...materials.Xuantra1Mtl}
            transparent={false}
            depthWrite={true}
            depthTest={true}
            side={THREE.FrontSide}
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/3Dassets/Avatar.glb')
